= Introducción

La primera entrega de este proyecto construyó `tourism-platform`, una plataforma multi-tenant desplegada sobre Kubernetes que expone una API REST para que distintas empresas de turismo consulten un catálogo de tours y gestionen reservas con aislamiento de datos por inquilino. Su arquitectura comprende cuatro microservicios desarrollados en FastAPI —un `api-gateway`, un servicio de autenticación, uno de tours y uno de reservas—, una base de datos PostgreSQL como `StatefulSet`, una caché Redis y un Ingress NGINX como punto de entrada, todo sobre un clúster Kind de tres nodos. Esa entrega demostró que el sistema funciona de extremo a extremo.

Esta segunda entrega no añade funcionalidad de negocio: profundiza en la capa de red, que es el foco natural del curso. Si la primera respondía a la pregunta "¿el sistema funciona?", esta responde a "¿es observable, seguro y resiliente como lo sería una red de servicios en producción?". Para ello se trabaja sobre tres ejes complementarios construidos encima de la plataforma existente, sin reescribir la lógica de negocio.

El primer eje introduce una malla de servicios con Linkerd, que cifra automáticamente con TLS mutuo (mTLS) todo el tráfico entre microservicios y aporta observabilidad del plano de datos —latencia y tasa de peticiones por servicio— sin modificar el código de la aplicación. El segundo aplica NetworkPolicies de mínimo privilegio, que restringen las conexiones únicamente a los flujos legítimos y reducen la superficie de movimiento lateral ante un eventual compromiso. El tercero incorpora autoescalado dinámico con KEDA, que ajusta las réplicas del servicio identificado como cuello de botella en función de una métrica real de la malla: su tasa de peticiones entrantes.

Los tres ejes siguen un hilo conductor —observar la red, asegurarla y hacerla resiliente bajo carga— y, además, cada fase informó a la siguiente: la observabilidad de la malla permitió localizar el cuello de botella del sistema, lo que a su vez determinó qué servicio convenía autoescalar. El objetivo general es, en consecuencia, evolucionar una plataforma funcional hacia una observable, segura a nivel de red y elástica, aplicando conceptos avanzados de redes —malla de servicios, mTLS, políticas de red y autoescalado guiado por métricas— sobre un entorno Kubernetes realista.

El resto del documento se organiza de la siguiente manera: el Capítulo 2 describe el entorno y las herramientas empleadas; los Capítulos 3, 4 y 5 desarrollan, respectivamente, la malla de servicios con mTLS, la segmentación con NetworkPolicies y el autoescalado con KEDA; un capítulo dedicado a problemas y soluciones reúne los hallazgos de integración más relevantes entre estas capas; y se cierra con las conclusiones y las líneas de trabajo futuro.
