= Conclusiones

Esta segunda entrega evolucionó `tourism-platform` desde una plataforma funcional hacia una observable, segura a nivel de red y elástica, sin reescribir su lógica de negocio. Los tres ejes —malla con mTLS, segmentación con NetworkPolicies y autoescalado con KEDA— se construyeron de forma incremental sobre el despliegue de la primera entrega, siguiendo el hilo de observar la red, asegurarla y hacerla resiliente.

La malla de servicios aportó cifrado mTLS automático entre todos los microservicios con un sobrecosto de latencia despreciable para la carga evaluada y, sobre todo, una observabilidad del plano de datos que resultó decisiva: permitió localizar el cuello de botella del sistema —el `api-gateway`— sin instrumentar el código de la aplicación. Ese hallazgo no solo caracterizó el comportamiento del sistema, sino que orientó las decisiones posteriores.

La seguridad de red se abordó en dos capas complementarias. El mTLS de la malla cifra el tráfico en tránsito y autentica a cada servicio, mientras que las NetworkPolicies de mínimo privilegio restringen qué pod puede comunicarse con cuál. La eficacia de esta segunda capa se verificó empíricamente: un pod no autorizado quedó bloqueado en todos los destinos sensibles. Juntas constituyen una defensa en profundidad: aunque un atacante comprometa un pod, ni puede leer el tráfico ajeno ni alcanzar servicios para los que no está autorizado.

El autoescalado con KEDA, guiado por la tasa de peticiones real que reporta la malla, demostró que el sistema puede ajustar su capacidad de forma autónoma ante la demanda y preservar la disponibilidad bajo carga. No obstante, el resultado más instructivo fue su límite: escalar el `api-gateway` mantuvo cero errores pero no redujo su latencia, porque la causa era de diseño —la creación de conexiones en cada petición— y no de capacidad. El autoescalado preserva la disponibilidad, pero no sustituye una arquitectura de aplicación correcta.

Buena parte del aprendizaje provino de la fricción entre capas, no del camino feliz. Validar empíricamente que kindnet ya aplicaba NetworkPolicies evitó una recreación destructiva del clúster; el incidente del puerto 4143 mostró que una política de capa 3/4 no puede gobernar puertos entre pods de la malla; y el rechazo HTTP 403 reveló que el modelo zero-trust de Linkerd alcanza incluso a su propio stack de observabilidad. Estos casos enseñaron cómo conviven —y a veces chocan— Kubernetes, la malla de servicios y las herramientas que se montan encima.

En conjunto, el trabajo cumple su objetivo: una plataforma de microservicios cifrada, segmentada y elástica sobre Kubernetes, con la observabilidad como hilo que conecta la seguridad y la resiliencia. Las líneas de mejora identificadas —políticas de egreso, autorización a nivel de aplicación (L7) y un pool de conexiones reutilizable en el `api-gateway`— quedan recogidas en el capítulo de trabajo futuro.
